//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pldt.Browser.Api.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRecord
    {
        public string id { get; set; }
        public string email { get; set; }
        public string jsonData { get; set; }
    }
}
